// The 2013 brush mark (jm), sampled into 208 points on a 7px grid.
// Values are percentages of the mark's 218×140 bounding box, [x0,y0, x1,y1, …].
// Generated by tools/images.mjs from 2013/img/logo.png.
export const MARK_ASPECT = 218 / 140;

// How big the mark wants to be in a canvas of w×h. It lives here, with the mark,
// because two places need it and cannot import each other: the page (main.js,
// which has a DOM) and the still renderer (tools/still.mjs, which has none). It
// was copied into both, and a copy is a thing that drifts — this one had to be
// hand-edited twice in one afternoon to keep the no-JS still matching the canvas.
// Pure by design: hand it numbers, it hands back a size.
//   • It GROWS with the room, and because a bird is one fixed size everywhere,
//     a wider mark is a wider point pitch — the flock spreads and thins.
//   • 840 is where it stops: past a ~2.6:1 pitch-to-wingspan the strokes stop
//     joining and the jm comes apart (the phone hits the same limit from the
//     other end, where the birds weld into a blob).
//   • The height term is desktop-only. On a phone it also shrank the LANDSCAPE
//     mark, which dropped it under the stand-down threshold and put a mark back
//     on a viewport with no room for one.
export const MARK_MAX = 840;
export function markSize(w, h, phone) {
  const bw = phone ? Math.min(w * 0.66, MARK_MAX)
                   : Math.min(w * 0.4, h * 0.58 * MARK_ASPECT, MARK_MAX);
  return { w: bw, h: bw / MARK_ASPECT };
}
export const MARK = new Uint8Array([37,3,40,3,14,8,18,8,21,8,24,8,27,8,31,8,34,8,37,8,40,8,43,8,11,13,14,13,18,13,21,13,24,13,27,13,31,13,34,13,37,13,40,13,43,13,47,13,50,13,8,18,18,18,21,18,24,18,27,18,31,18,34,18,37,18,40,18,43,18,47,18,50,18,43,23,47,23,50,23,47,28,50,28,53,28,47,33,50,33,53,33,47,38,50,38,53,38,47,43,50,43,53,43,56,43,47,48,50,48,53,48,56,48,31,53,34,53,37,53,40,53,43,53,47,53,50,53,53,53,56,53,59,53,63,53,72,53,76,53,79,53,82,53,85,53,24,57,31,57,34,57,37,57,40,57,43,57,47,57,50,57,53,57,56,57,59,57,63,57,66,57,69,57,72,57,76,57,79,57,82,57,85,57,88,57,92,57,21,63,24,63,27,63,31,63,34,63,37,63,40,63,43,63,47,63,50,63,53,63,59,63,63,63,66,63,69,63,72,63,76,63,79,63,82,63,85,63,88,63,92,63,95,63,21,68,24,68,27,68,31,68,34,68,47,68,50,68,53,68,63,68,66,68,69,68,72,68,76,68,79,68,82,68,85,68,88,68,92,68,95,68,98,68,18,73,21,73,24,73,27,73,47,73,50,73,53,73,63,73,66,73,69,73,72,73,92,73,95,73,98,73,18,78,21,78,24,78,43,78,47,78,50,78,53,78,63,78,66,78,69,78,72,78,92,78,95,78,98,78,18,83,21,83,24,83,27,83,31,83,34,83,37,83,40,83,43,83,47,83,50,83,63,83,66,83,69,83,72,83,92,83,95,83,98,83,21,88,24,88,27,88,31,88,34,88,37,88,40,88,43,88,47,88,50,88,63,88,66,88,72,88,92,88,95,88,98,88,24,93,31,93,34,93,40,93,43,93,66,93,69,93,72,93,95,93]);
